In [2]:
import numpy as np
import pandas as pd

# Each variable is a column.
# Each observation is a row.
# Each type of observation has its own separate data frame.

df = pd.read_csv("./git/bootcamp/data/gfmt_sleep.csv")
df["insomnia"] = df["sci"] <= 16
df.head()

,participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence when incorrect hit,confidence when correct reject,confidence when incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess,insomnia
0,8,f,39,65,80,72.5,91.0,90,93.0,83.5,93.0,90,9,13,2,True
1,16,m,42,90,90,90.0,75.5,55.5,70.5,50,75.0,50,4,11,7,True
2,18,f,31,90,95,92.5,89.5,90,86.0,81,89.0,88,10,9,3,True
3,22,f,35,100,75,87.5,89.5,*,71.0,80,88.0,80,13,8,20,True
4,27,f,74,60,65,62.5,68.5,49,61.0,49,65.0,49,13,9,12,True

In [3]:
# Split - Apply - Combine => Aggregation
# Split
grouped = df.groupby(['insomnia', 'gender'])

# Apply & Combine (Median)
df_median = grouped.median(numeric_only=True)
# df_median

df_median = df_median.reset_index()
df_median

,insomnia,gender,participant number,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence when correct reject,confidence when correct,sci,psqi,ess
0,False,f,58.0,36.0,85.0,80.0,85.00,74.00,70.50,74.00,26.0,4.0,7.0
1,False,m,41.0,38.5,90.0,80.0,82.50,76.00,74.25,76.25,29.0,3.0,6.0
2,True,f,46.0,39.0,80.0,75.0,72.50,76.50,71.00,77.00,14.0,9.0,7.0
3,True,m,55.5,37.0,95.0,82.5,83.75,83.75,75.75,81.25,14.0,9.0,8.0

In [4]:
# Transformation anstelle von Aggregation
df["rank grouped by insomnia"] = grouped["percent correct"].rank(
    method="first")

df.head()

,participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence when incorrect hit,confidence when correct reject,confidence when incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess,insomnia,rank grouped by insomnia
0,8,f,39,65,80,72.5,91.0,90,93.0,83.5,93.0,90,9,13,2,True,10.0
1,16,m,42,90,90,90.0,75.5,55.5,70.5,50,75.0,50,4,11,7,True,5.0
2,18,f,31,90,95,92.5,89.5,90,86.0,81,89.0,88,10,9,3,True,18.0
3,22,f,35,100,75,87.5,89.5,*,71.0,80,88.0,80,13,8,20,True,15.0
4,27,f,74,60,65,62.5,68.5,49,61.0,49,65.0,49,13,9,12,True,3.0

In [5]:
# SOrtierung der transformierten Werte
df_sorted = df.sort_values(by=["insomnia", "percent correct"])
df_sorted[["insomnia","percent correct","rank grouped by insomnia"]]

    insomnia  percent correct  rank grouped by insomnia
81     False             40.0                       1.0
94     False             55.0                       1.0
39     False             57.5                       2.0
76     False             60.0                       2.0
96     False             60.0                       3.0
..       ...              ...                       ...
1       True             90.0                       5.0
8       True             90.0                      17.0
2       True             92.5                      18.0
11      True             95.0                      19.0
21      True             97.5                       6.0

[102 rows x 3 columns]

In [6]:
import numpy as np
# Berechnung des Variationskoeffizienten
# V = S / M


def coeff(data=1):
    # print(data)
    # print(np.mean(data))
    result = np.std(data)/np.mean(data)
    return result

# TODO
# ValueError
grouped.agg(coeff)

TypeError: could not convert string to float: '*'

In [7]:
# Berechnung der Empirischen kumulativen Verteilungsfunktion

def ecdf_y(data):
    """Give y-values of an ECDF for an unsorted column in a data frame."""
    return data.rank(method='first') / len(data)

df['ecdf_y grouped by insomnia'] = grouped['percent correct'].transform(ecdf_y)
df.head()

,participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence when incorrect hit,confidence when correct reject,confidence when incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess,insomnia,rank grouped by insomnia,ecdf_y grouped by insomnia
0,8,f,39,65,80,72.5,91.0,90,93.0,83.5,93.0,90,9,13,2,True,10.0,0.526316
1,16,m,42,90,90,90.0,75.5,55.5,70.5,50,75.0,50,4,11,7,True,5.0,0.833333
2,18,f,31,90,95,92.5,89.5,90,86.0,81,89.0,88,10,9,3,True,18.0,0.947368
3,22,f,35,100,75,87.5,89.5,*,71.0,80,88.0,80,13,8,20,True,15.0,0.789474
4,27,f,74,60,65,62.5,68.5,49,61.0,49,65.0,49,13,9,12,True,3.0,0.157895

In [8]:
df.groupby(['gender', 'insomnia'])['percent correct'].describe()

                 count       mean        std   min     25%    50%     75%
gender insomnia
f      False      55.0  82.045455  10.844982  55.0  75.000  85.00  88.750  \
       True       19.0  73.947368  13.624829  45.0  67.500  72.50  83.750
m      False      22.0  80.000000  12.770875  40.0  77.500  82.50  89.375
       True        6.0  82.916667  10.655593  67.5  76.875  83.75  88.750

                   max
gender insomnia
f      False     100.0
       True       95.0
m      False      95.0
       True       97.5

In [9]:
# Berechnung der Median für die Gruppierung Geschlecht & Schlaflosigkeit
for name, group in df.groupby(['gender', 'insomnia']):
    print(name, ': ', group['percent correct'].median())

('f', False) :  85.0
('f', True) :  72.5
('m', False) :  82.5
('m', True) :  83.75

In [10]:
# Laden eines CSV-Files mit Daten
df = pd.read_csv('git/bootcamp/data/reeves_gradient_width_various_methods.csv', comment='#', header=[0,1])

df.head()

# Funktionsaufruf von melt mit den Variablen und dem Wert
df = pd.melt(df, value_name='gradient width', var_name=['genotype', 'method'])
# Entfernung der NaN-Werten
df = df.dropna()

df.head()
# Split Anhand
df.groupby(['genotype', 'method']).describe()

                                 gradient width
                                          count      mean       std     min
genotype          method
dl1/+; dl-gfp/+   GFP (live)                6.0  0.218783  0.021052  0.1942  \
                  anti-Dorsal              20.0  0.198300  0.024468  0.1640
                  anti-GFP                 20.0  0.226120  0.024664  0.1934
dl1/+; dl-venus/+ Venus (live)              3.0  0.170800  0.004358  0.1666
                  anti-Dorsal              29.0  0.160490  0.010805  0.1342
                  anti-Venus               29.0  0.173031  0.008742  0.1483
wt                cross-sections          152.0  0.148458  0.016141  0.1014
                  wholemounts              24.0  0.145279  0.019059  0.1096


                                       25%      50%       75%     max
genotype          method
dl1/+; dl-gfp/+   GFP (live)      0.204100  0.21450  0.235550  0.2463
                  anti-Dorsal     0.177625  0.19540  0.213775  0.2516
                  anti-GFP        0.203950  0.22620  0.241550  0.2682
dl1/+; dl-venus/+ Venus (live)    0.168550  0.17050  0.172900  0.1753
                  anti-Dorsal     0.154600  0.16010  0.170100  0.1773
                  anti-Venus      0.170100  0.17390  0.178000  0.1902
wt                cross-sections  0.136725  0.14695  0.159925  0.1805
                  wholemounts     0.130450  0.14460  0.158200  0.1779

In [11]:
%load_ext watermark
%watermark -v -p numpy,pandas,jupyterlab

Python implementation: CPython
Python version       : 3.11.1
IPython version      : 8.12.0

numpy     : 1.24.3
pandas    : 2.0.1
jupyterlab: 3.6.3